const EX=[
{id:'bench',name:'Dumbbell Bench Press',muscle:'Chest',sets:3,min:6,max:10,rpe:'7–8',rest:120,last:[{w:50,r:10},{w:50,r:9},{w:45,r:10}],cue:'Drive your feet into the floor. Keep wrists stacked and lower with control.'},
{id:'incline',name:'Incline Machine Press',muscle:'Chest',sets:3,min:8,max:12,rpe:'7–8',rest:90,last:[{w:70,r:12},{w:70,r:11},{w:70,r:10}],cue:'Set the handles near upper chest. Keep shoulder blades back.'},
{id:'shoulder',name:'Machine Shoulder Press',muscle:'Shoulders',sets:2,min:8,max:12,rpe:'7',rest:90,last:[{w:55,r:10},{w:55,r:9}],cue:'Use a pain-free grip. Keep ribs down and avoid shrugging.'},
{id:'fly',name:'Cable Chest Fly',muscle:'Chest',sets:2,min:12,max:15,rpe:'8',rest:60,last:[{w:20,r:15},{w:20,r:13}],cue:'Soft elbows. Squeeze the chest without over-stretching.'},
{id:'lateral',name:'Cable Lateral Raise',muscle:'Shoulders',sets:3,min:12,max:20,rpe:'8',rest:45,last:[{w:10,r:18},{w:10,r:16},{w:10,r:15}],cue:'Lead with the elbow. Stop around shoulder height and avoid swinging.'},
{id:'pressdown',name:'Rope Triceps Pressdown',muscle:'Triceps',sets:3,min:12,max:15,rpe:'7–8',rest:60,last:[{w:35,r:15},{w:35,r:14},{w:35,r:12}],cue:'Pin elbows to your sides. Separate the rope at the bottom.'},
{id:'walk',name:'Treadmill Walk',muscle:'Cardio',sets:1,min:10,max:15,rpe:'Easy',rest:0,last:[{w:0,r:12}],cue:'Easy to moderate pace. You should still be able to speak in full sentences.',cardio:true}
];
const KEY='bodysmith-mvp-v1',app=document.querySelector('#app');
const S={screen:'workout',detail:null,session:null,summary:null,rest:0,timer:null};
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}};
const save=x=>localStorage.setItem(KEY,JSON.stringify({...load(),...x}));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
const dur=ms=>{const s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
function header(title,{back=false,finish=false}={}){return `<header class="topbar"><button class="iconbtn" data-action="${back?'back':'noop'}">${back?'←':'BS'}</button><div class="grow"><div class="brand">${title==='BodySmith'?'Body<span>Smith</span>':esc(title)}</div>${title==='BodySmith'?'<div class="tag">BUILD A STRONGER YOU</div>':''}</div>${finish?'<button class="iconbtn" data-action="finish">Finish</button>':'<div class="avatar">MS</div>'}</header>`}
function nav(){return `<nav class="bottom-nav">${[['plan','▣'],['exercises','🏋'],['workout','▰'],['progress','▤'],['profile','◎']].map(([n,i])=>`<button data-nav="${n}" class="${S.screen===n?'active':''}"><span>${i}</span><small>${n[0].toUpperCase()+n.slice(1)}</small></button>`).join('')}</nav>`}
function art(ex,large=false){return `<div class="${large?'detail-hero':'thumb'}"><svg viewBox="0 0 260 160"><rect width="260" height="160" rx="16" fill="#f7f8fb"/><g stroke="#969eab" stroke-width="5" fill="none" stroke-linecap="round"><path d="M35 130h190"/><path d="M70 130l15-35h95l15 35"/></g><g stroke="#505866" stroke-width="10" fill="none" stroke-linecap="round"><circle cx="132" cy="45" r="15" fill="#d9dde5" stroke-width="3"/><path d="M132 62v40M132 74l-38-25M132 74l42-25M132 102l-28 36M132 102l34 36"/></g><g fill="#ff5b3d"><ellipse cx="120" cy="77" rx="13" ry="10"/><ellipse cx="144" cy="77" rx="13" ry="10"/></g><text x="14" y="24" fill="#111827" font-size="14" font-weight="700">${esc(ex.name)}</text><text x="14" y="44" fill="#6b7280" font-size="11">Primary: ${esc(ex.muscle)}</text></svg></div>`}
function home(){return `<div class="screen">${header('BodySmith')}<section class="card plan"><div class="bolt">⚡</div><div><span class="muted">Active Plan</span><h2>Michael Muscle Builder</h2><p>4-day split • Build muscle • Level 3</p></div></section><div class="section-title"><h1>Your next workout</h1><span class="muted">Today</span></div><section class="card"><div class="workout-head"><div><h2>Push Day</h2><p class="muted">Chest + Shoulders + Triceps</p></div><span class="pill">7 exercises</span></div>${EX.map(ex=>`<button class="exercise-row" data-ex="${ex.id}">${art(ex)}<div class="exercise-copy"><strong>${ex.name}</strong><span>${ex.cardio?'10–15 min':`${ex.sets} sets × ${ex.min}–${ex.max} reps`}</span></div><div class="muscle">${ex.muscle}</div><span class="chev">›</span></button>`).join('')}<button class="primary huge" data-action="start">Start Workout</button></section>${nav()}</div>`}
function detail(ex){return `<div class="screen">${header(ex.name,{back:true})}${art(ex,true)}<button class="primary huge" data-action="start">Start Workout</button><section class="panel"><h3>Exercise Note</h3><p>${ex.cue}</p></section><div class="detail-stats"><div class="stat"><span>Movement</span><strong>${ex.cardio?'Cardio':'Push'}</strong></div><div class="stat"><span>Target RPE</span><strong>${ex.rpe}</strong></div><div class="stat"><span>Rest</span><strong>${ex.rest?`${ex.rest}s`:'—'}</strong></div></div><div class="tabs"><button class="active">Max Weight</button><button>Volume</button><button>Power (1RM)</button></div><section class="panel"><h3>Max Weight Progress</h3><p class="muted">Last 5 sessions trending up</p><h1>${ex.cardio?'12 min':`${Math.max(...ex.last.map(x=>x.w))} lb × ${Math.max(...ex.last.map(x=>x.r))}`}</h1><svg class="spark" viewBox="0 0 300 100"><polyline points="10,82 72,68 132,59 198,42 288,22" fill="none" stroke="#2487ff" stroke-width="5"/>${[[10,82],[72,68],[132,59],[198,42],[288,22]].map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="6" fill="#fff" stroke="#2487ff" stroke-width="4"/>`).join('')}</svg></section>${nav()}</div>`}
function active(){const s=S.session,ex=EX[s.i],logs=s.logs[ex.id]||[],planned=EX.reduce((n,e)=>n+e.sets,0),logged=Object.values(s.logs).reduce((n,a)=>n+a.length,0),pct=Math.round(logged/planned*100),cur=Math.min(logs.length+1,ex.sets),prev=ex.last[Math.min(logs.length,ex.last.length-1)]||{};return `<div class="screen">${header('Push Workout',{finish:true})}<div class="session-strip"><span>Time ${dur(Date.now()-s.started)}</span><span>${pct}% complete</span></div><div class="progress"><div style="width:${pct}%"></div></div>${art(ex,true)}${S.rest>0?`<div class="rest"><span>Rest timer</span><strong>${fmt(S.rest)}</strong><button data-action="skiprest">Skip</button></div>`:''}<div class="active-title"><div><h1>${ex.name}</h1><p class="muted">${ex.cardio?'Cardio finisher':`${ex.rest} sec rest`}</p></div><span class="setcount">Set ${cur}/${ex.sets}</span></div><div class="chips"><span>${ex.sets} sets</span><span>${ex.min}–${ex.max} reps</span><span>RPE ${ex.rpe}</span><span>${ex.muscle}</span></div><section class="panel"><b>Coach cue</b><p>${ex.cue}</p></section><div id="pain"></div><div class="set-table"><div class="set-head"><span>Set</span><span>Last</span><span>${ex.cardio?'Minutes':'Reps'}</span><span>${ex.cardio?'Pace':'Lb'}</span></div>${Array.from({length:ex.sets}).map((_,i)=>{const l=logs[i],p=ex.last[i],current=i===logs.length;return `<div class="set-line ${current?'current':''}"><b>${i+1}</b><span>${p?(ex.cardio?`${p.r} min`:`${p.r} × ${p.w}`):'—'}</span><span>${l?l.r:(current?`<input id="reps" value="${ex.cardio?'':(prev.r||ex.min)}" inputmode="decimal"/>`:'—')}</span><span>${l?(ex.cardio?'Moderate':l.w):(current?(ex.cardio?'<span class="muted">Moderate</span>':`<input id="weight" value="${prev.w||''}" inputmode="decimal"/>`):'—')}</span></div>`}).join('')}</div><div class="quick"><label>RPE<input id="rpe" value="${ex.cardio?'Easy':'7.5'}" inputmode="decimal"/></label><label>Elbow pain<input id="painInput" value="0" inputmode="numeric" min="0" max="10"/></label></div><button class="primary huge" data-action="log">✓ Log Set</button><div class="workout-nav"><button data-action="prev">← Previous</button><button data-action="next">Next →</button></div></div>`}
function summary(){const s=S.summary,all=Object.values(s.logs).flat(),total=all.length,planned=EX.reduce((n,e)=>n+e.sets,0),pct=Math.min(100,Math.round(total/planned*100)),avg=all.length?(all.reduce((n,x)=>n+(Number(x.rpe)||0),0)/all.length).toFixed(1):'—',pain=all.length?(all.reduce((n,x)=>n+(Number(x.pain)||0),0)/all.length).toFixed(1):'0';return `<div class="screen">${header('BodySmith')}<h1>Workout Summary</h1><h2 style="color:#64aaff">Push Day Complete</h2><p class="muted">Great work, Michael. Consistency builds results.</p><section class="card score"><div class="ring" style="--pct:${pct*3.6}deg"><strong>${pct}%</strong><span>COMPLETE</span></div><div><span class="muted">BodySmith Score</span><h1>+${Math.max(1,Math.round(pct/8))}</h1><span style="color:#2f97ff">▲</span></div></section><div class="summary-grid">${[['Duration',dur(Date.now()-s.started)],['Exercises',`${Object.keys(s.logs).filter(k=>s.logs[k].length).length}/7`],['Sets Logged',total],['Avg RPE',avg],['Elbow Pain',`${pain}/10`]].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join('')}</div><section class="panel"><h3>Completed Exercises</h3>${EX.map(ex=>`<div class="summary-row">${art(ex)}<div><strong>${ex.name}</strong><span class="muted">${s.logs[ex.id]?.length||0}/${ex.sets} sets logged</span></div><span class="${s.logs[ex.id]?.length>=ex.sets?'check':'muted'}">${s.logs[ex.id]?.length>=ex.sets?'✓':'•'}</span></div>`).join('')}</section><section class="panel"><h3>Coach Notes</h3><p>${coach(s)}</p></section><button class="primary huge" data-action="savefinish">✓ Save & Finish</button></div>`}
function coach(s){const bench=s.logs.bench||[];if(bench.length>=3&&bench.every(x=>x.r>=10&&Number(x.rpe)<=8))return 'Bench press hit the top rep range at target effort. Add 5 lb next session if form stays clean.';const p=Math.max(0,...Object.values(s.logs).flat().map(x=>Number(x.pain)||0));if(p>=6)return 'A movement reached 6+/10 elbow pain. Swap that movement next session and keep the replacement pain-free.';if(p>=4)return 'Elbow pain reached the caution range. Reduce load or arm volume next session if needed.';return 'Good session. Add reps within the target ranges before increasing load.'}
function placeholder(n){return `<div class="screen">${header(n)}<div class="placeholder"><b>BODYSMITH</b><h1>${n}</h1><p class="muted">This MVP is focused on the complete Push Day workout loop. This section is ready for the next build phase.</p></div>${nav()}</div>`}
function render(){if(S.screen==='active'&&S.session)app.innerHTML=active();else if(S.screen==='summary'&&S.summary)app.innerHTML=summary();else if(S.detail)app.innerHTML=detail(S.detail);else if(S.screen==='workout')app.innerHTML=home();else app.innerHTML=placeholder(S.screen[0].toUpperCase()+S.screen.slice(1));bind()}
function start(){S.session={id:`push-${Date.now()}`,started:Date.now(),i:0,logs:{}};S.screen='active';S.detail=null;save({active:S.session});render()}
function rest(sec){S.rest=sec;clearInterval(S.timer);if(sec>0)S.timer=setInterval(()=>{S.rest=Math.max(0,S.rest-1);if(!S.rest)clearInterval(S.timer);const el=document.querySelector('.rest strong');if(el)el.textContent=fmt(S.rest)},1000)}
function log(){const s=S.session,ex=EX[s.i],logs=s.logs[ex.id]||[],entry={r:Number(document.querySelector('#reps')?.value||ex.min),w:Number(document.querySelector('#weight')?.value||0),rpe:document.querySelector('#rpe')?.value||0,pain:Number(document.querySelector('#painInput')?.value||0)};s.logs={...s.logs,[ex.id]:[...logs,entry]};if(s.logs[ex.id].length>=ex.sets&&s.i<EX.length-1)s.i++;save({active:s});rest(ex.rest);render()}
function pain(){const n=Number(document.querySelector('#painInput')?.value||0),b=document.querySelector('#pain');if(b)b.innerHTML=n>=6?'<div class="pain danger">Stop or swap this movement. Pain is 6+/10.</div>':n>=4?'<div class="pain">Pain is 4+/10. Reduce load or use a pain-free variation.</div>':''}
function finish(){S.summary=S.session;S.screen='summary';render()}
function saveFinish(){const st=load(),history={...(st.history||{})};Object.entries(S.summary.logs).forEach(([k,v])=>{if(v.length)history[k]=v});save({history,lastWorkout:{...S.summary,finished:Date.now()},active:null});S.session=null;S.summary=null;S.screen='workout';render()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{S.screen=b.dataset.nav;S.detail=null;render()});document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>{S.detail=EX.find(x=>x.id===b.dataset.ex);render()});document.querySelectorAll('[data-action]').forEach(b=>{const a=b.dataset.action;if(a==='start')b.onclick=start;if(a==='back')b.onclick=()=>{S.detail=null;render()};if(a==='finish')b.onclick=finish;if(a==='log')b.onclick=log;if(a==='skiprest')b.onclick=()=>{S.rest=0;render()};if(a==='prev')b.onclick=()=>{S.session.i=Math.max(0,S.session.i-1);render()};if(a==='next')b.onclick=()=>{S.session.i=Math.min(EX.length-1,S.session.i+1);render()};if(a==='savefinish')b.onclick=saveFinish});const p=document.querySelector('#painInput');if(p)p.oninput=pain}
const st=load();if(st.active){S.session=st.active;S.screen='active'}render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));