(()=>{
  const TOKEN_KEY='bodysmith-token-v2';
  const API_KEY='sb_publishable_ibEVVafS4THz-16p4euMfg_qjG2WeU2';
  const PLANNER_URL='https://uuzctytbguqjumwpczfh.supabase.co/functions/v1/bodysmith-planner';
  const CORE_URL='https://uuzctytbguqjumwpczfh.supabase.co/functions/v1/bodysmith-api';
  const state={loaded:false,loading:false,error:'',events:[],plans:[],enrollments:[],month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedPlanId:'',program:'pushup',active:null};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const token=()=>localStorage.getItem(TOKEN_KEY)||'';
  const cacheKey=()=>token()?'bodysmith-cache-v3-'+token().slice(-24):'';
  function cache(){try{return JSON.parse(localStorage.getItem(cacheKey())||'null')}catch{return null}}
  const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const parseLocal=s=>{const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)};
  const addDays=(s,n)=>{const d=parseLocal(s);d.setDate(d.getDate()+n);return localDate(d)};
  const toast=(msg,error=false)=>{const el=document.getElementById('toast');if(!el){alert(msg);return}el.textContent=msg;el.className=`show${error?' error':''}`;clearTimeout(el._plannerTimer);el._plannerTimer=setTimeout(()=>el.className='',3200)};
  async function call(url,action,payload={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY},body:JSON.stringify({action,...payload,token:token()})});const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Error(d.error||'Request failed.');return d}
  const planner=(a,p)=>call(PLANNER_URL,a,p),core=(a,p)=>call(CORE_URL,a,p);
  const programName=k=>k==='pushup'?'Push-Up Progression':k==='pullup'?'Pull-Up Progression':'Push + Pull Progression';
  function targetText(e){const t=e?.target||{},bits=[];if(t.pushups)bits.push(`${t.pushups} push-ups total`);if(t.pullups)bits.push(`${t.pullups} pull-ups total`);return bits.join(' · ')}
  async function load(force=false){if(state.loading||state.loaded&&!force)return;state.loading=true;state.error='';try{const t=localDate(),d=await planner('bootstrap',{from:addDays(t,-120),to:addDays(t,210)});state.events=d.events||[];state.plans=d.plans||[];state.enrollments=d.enrollments||[];state.loaded=true;if(!state.selectedPlanId)state.selectedPlanId=(state.plans.find(p=>p.id===cache()?.user?.active_plan_id)||state.plans[0])?.id||'';}catch(e){state.error=e.message||'Calendar could not load.'}finally{state.loading=false;renderOverlayIfOpen();enhance()}}
  function historyByDate(){const map={};for(const h of cache()?.history||[]){if(h.status!=='completed')continue;const k=localDate(new Date(h.started_at));(map[k]??=[]).push(h)}return map}
  function eventMap(){const map={};for(const e of state.events)(map[e.scheduled_date]??=[]).push(e);return map}
  function monthGrid(){const m=state.month,y=m.getFullYear(),mo=m.getMonth(),first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay()),events=eventMap(),hist=historyByDate(),today=localDate(),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=localDate(d),outside=d.getMonth()!==mo,ev=events[k]||[],done=hist[k]||[];cells.push(`<div class="calendar-day ${outside?'outside':''} ${k===today?'today':''}"><div class="calendar-date">${d.getDate()}</div>${done.length?`<span class="calendar-chip done">✓ ${done.length} completed</span>`:''}${ev.slice(0,3).map(x=>`<span class="calendar-chip ${x.kind} ${x.status==='planned'&&k<today?'missed':''}">${x.kind==='rest'?'Rest':x.kind==='note'?'Note':x.status==='completed'?'Done':'Workout'}</span>`).join('')}${ev.length>3?`<span class="calendar-more">+${ev.length-3}</span>`:''}</div>`)}return `<div class="calendar-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div>`}
  function category(p){const n=(p.name+' '+(p.goal||'')).toLowerCase();if(/progression/.test(n))return'Progressions';if(/1 day|focus|standalone/.test(n))return'Body-part / single-day';if(/home|minimal/.test(n))return'Home & minimal equipment';if(/fat loss|muscle gain|strength foundation|beginner/.test(n))return'Goal-based';return'Splits & routines'}
  function presetLibrary(){const list=state.plans.filter(p=>p.is_template),groups={};for(const p of list)(groups[category(p)]??=[]).push(p);return `<section class="panel preset-library"><div class="mini-row"><div><span class="eyebrow">PRESET LIBRARY</span><h3 style="margin:3px 0">More ways to train</h3></div><span class="pill">${list.length} presets</span></div><p class="muted tiny">Choose a preset to make it your active plan. You can still pick any workout focus in that plan when you train.</p>${Object.entries(groups).map(([g,items])=>`<div class="preset-group"><h4>${esc(g)}</h4><div class="preset-grid">${items.map(p=>`<button class="preset-card" type="button" data-use-preset="${p.id}"><strong>${esc(p.name)}</strong><small>${p.days_per_week} day${p.days_per_week===1?'':'s'} / week</small><span>${esc(p.goal||'Training plan')}</span></button>`).join('')}</div></div>`).join('')}</section>`}
  function schedulePanel(){const p=state.plans.find(x=>x.id===state.selectedPlanId)||state.plans[0],days=p?.plan_days||[];return `<section class="panel"><span class="eyebrow">SCHEDULE</span><h3>Put a workout on the calendar</h3><label class="field">Plan<select id="plannerPlan">${state.plans.map(x=>`<option value="${x.id}" ${x.id===p?.id?'selected':''}>${esc(x.name)}${x.is_template?' · Preset':' · Yours'}</option>`).join('')}</select></label><label class="field">Workout<select id="plannerDay">${days.map(d=>`<option value="${d.id}">${esc(d.name)}${d.focus?' · '+esc(d.focus):''}</option>`).join('')}</select></label><label class="field">Date<input id="plannerDate" type="date" value="${localDate()}"></label><div class="row-actions"><button class="primary" data-planner-schedule>Schedule workout</button><button class="secondary" data-planner-rest>Add rest day</button></div></section>`}
  function progressionPanel(){const k=state.program;return `<section class="panel progression-panel"><span class="eyebrow">4-WEEK PROGRAMS</span><h3>Push-up & pull-up progression</h3><p class="muted">Enter a comfortable max set. BodySmith builds three training sessions per week with recovery days and gradually raises total volume.</p>${state.enrollments.length?`<div class="active-programs">${state.enrollments.map(x=>`<div class="mini-row"><div><strong>${esc(programName(x.program_key))}</strong><div class="muted tiny">Started ${esc(x.start_date)}</div></div><button class="secondary" data-cancel-program="${x.program_key}">Cancel</button></div>`).join('')}</div>`:''}<label class="field">Program<select id="progressionProgram"><option value="pushup" ${k==='pushup'?'selected':''}>Push-Up Progression</option><option value="pullup" ${k==='pullup'?'selected':''}>Pull-Up Progression</option><option value="pushpull" ${k==='pushpull'?'selected':''}>Push + Pull Progression</option></select></label>${k!=='pullup'?'<label class="field">Comfortable max push-ups in one set<input id="baselinePushups" type="number" min="1" max="500" inputmode="numeric" placeholder="Example: 15"></label>':''}${k!=='pushup'?'<label class="field">Comfortable max pull-ups in one set<input id="baselinePullups" type="number" min="1" max="200" inputmode="numeric" placeholder="Example: 5"></label>':''}<label class="field">Start date<input id="programStart" type="date" value="${localDate()}"></label><button class="primary huge" data-start-program>Build my 4-week calendar</button><p class="muted tiny">Example: a comfortable max of 15 push-ups begins around 45 total reps on the first volume day, divided over several sets. Rest days are automatically placed between sessions.</p></section>`}
  function eventList(){const today=localDate(),items=state.events.filter(e=>e.scheduled_date>=addDays(today,-7)).sort((a,b)=>a.scheduled_date.localeCompare(b.scheduled_date)).slice(0,35);if(!items.length)return'<section class="panel empty">Nothing scheduled yet.</section>';return `<section class="panel"><h3>Upcoming & recent</h3>${items.map(e=>{const target=targetText(e),missed=e.status==='planned'&&e.scheduled_date<today;return `<article class="planner-event ${e.kind} ${missed?'missed':''}"><div><strong>${esc(e.title)}</strong><div class="muted tiny">${parseLocal(e.scheduled_date).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}${missed?' · Missed / not logged':''}</div>${target?`<div class="target-line">${esc(target)}</div>`:''}</div><div class="planner-event-actions">${e.kind==='workout'?`<button class="primary" data-start-event="${e.id}">Start</button>`:''}${e.status==='planned'?`<button class="secondary" data-event-done="${e.id}">Mark done</button>`:''}<button class="linkbtn danger-text" data-delete-event="${e.id}">Remove</button></div></article>`}).join('')}</section>`}
  function overlayHtml(){return `<div class="nutrition-shell planner-shell"><header class="nutrition-topbar"><button class="iconbtn" data-planner-close aria-label="Back">←</button><div class="grow"><h1>Training Calendar</h1><div class="muted tiny">Presets · progression · recovery · completed workouts</div></div></header><section class="panel calendar-panel"><div class="calendar-head"><button class="secondary" data-planner-month="-1">←</button><h2>${state.month.toLocaleDateString([],{month:'long',year:'numeric'})}</h2><button class="secondary" data-planner-month="1">→</button></div>${state.error?`<div class="form-error">${esc(state.error)}</div>`:''}${state.loading&&!state.loaded?'<div class="empty">Loading calendar…</div>':monthGrid()}</section>${state.loaded?schedulePanel()+progressionPanel()+eventList():'<section class="panel empty">Loading schedule tools…</section>'}</div>`}
  function open(){if(!token())return;let el=document.getElementById('plannerOverlay');if(!el){el=document.createElement('div');el.id='plannerOverlay';el.className='nutrition-overlay';document.body.appendChild(el)}document.body.style.overflow='hidden';renderOverlayIfOpen();load()}
  function close(){document.getElementById('plannerOverlay')?.remove();document.body.style.overflow=''}
  function renderOverlayIfOpen(){const el=document.getElementById('plannerOverlay');if(!el)return;el.innerHTML=overlayHtml();bindOverlay(el)}
  async function startEvent(event){const c=cache();if(c?.active)throw Error('Finish or change your active workout first.');let action,payload;if(event.plan_day_id&&event.plan_id===c?.user?.active_plan_id){action='start_session';payload={planDayId:event.plan_day_id}}else{action='start_custom_session';payload={day:event.custom_snapshot}};await core(action,payload);localStorage.setItem('bodysmith-auto-resume','1');location.reload()}
  function bindOverlay(el){el.querySelector('[data-planner-close]').onclick=close;el.querySelectorAll('[data-planner-month]').forEach(b=>b.onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+Number(b.dataset.plannerMonth),1);renderOverlayIfOpen()});const sel=el.querySelector('#plannerPlan');if(sel)sel.onchange=()=>{state.selectedPlanId=sel.value;renderOverlayIfOpen()};const prog=el.querySelector('#progressionProgram');if(prog)prog.onchange=()=>{state.program=prog.value;renderOverlayIfOpen()};const schedule=el.querySelector('[data-planner-schedule]');if(schedule)schedule.onclick=async()=>{schedule.disabled=true;try{const date=el.querySelector('#plannerDate').value,day=el.querySelector('#plannerDay').value;if(!day)throw Error('Choose a workout.');await planner('schedule',{date,kind:'workout',planDayId:day});toast('Workout scheduled');await load(true)}catch(e){toast(e.message,true)}finally{schedule.disabled=false}};const rest=el.querySelector('[data-planner-rest]');if(rest)rest.onclick=async()=>{rest.disabled=true;try{await planner('schedule',{date:el.querySelector('#plannerDate').value,kind:'rest',title:'Rest / Recovery'});toast('Rest day scheduled');await load(true)}catch(e){toast(e.message,true)}finally{rest.disabled=false}};el.querySelectorAll('[data-start-event]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const e=state.events.find(x=>x.id===b.dataset.startEvent);if(e)await startEvent(e)}catch(err){toast(err.message,true);b.disabled=false}});el.querySelectorAll('[data-event-done]').forEach(b=>b.onclick=async()=>{try{await planner('set_status',{eventId:b.dataset.eventDone,status:'completed'});await load(true)}catch(e){toast(e.message,true)}});el.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this item from the calendar?'))return;try{await planner('delete_event',{eventId:b.dataset.deleteEvent});await load(true)}catch(e){toast(e.message,true)}});const start=el.querySelector('[data-start-program]');if(start)start.onclick=async()=>{start.disabled=true;try{const k=state.program,push=el.querySelector('#baselinePushups')?.value,pull=el.querySelector('#baselinePullups')?.value,startDate=el.querySelector('#programStart').value;await planner('enroll_program',{programKey:k,baselinePushups:push?Number(push):null,baselinePullups:pull?Number(pull):null,startDate});toast(`${programName(k)} added to calendar`);await load(true)}catch(e){toast(e.message,true)}finally{start.disabled=false}};el.querySelectorAll('[data-cancel-program]').forEach(b=>b.onclick=async()=>{if(!confirm(`Cancel ${programName(b.dataset.cancelProgram)}?`))return;try{await planner('cancel_program',{programKey:b.dataset.cancelProgram});await load(true)}catch(e){toast(e.message,true)}})}
  function launchCard(where){const s=document.createElement('section');s.className='panel planner-launch '+where;s.innerHTML=`<div><span class="eyebrow">TRAINING CALENDAR</span><h3>Plan workouts around real life</h3><p class="muted tiny">Schedule presets or custom plans, see completed days, rest days, missed days, and progression programs.</p></div><button class="primary" data-open-planner>Open Calendar</button>`;s.querySelector('[data-open-planner]').onclick=open;return s}
  function injectPresetLibrary(){if(!state.loaded||document.querySelector('.preset-library'))return;const heading=[...document.querySelectorAll('h2')].find(x=>x.textContent.trim()==='Find your routine');const panel=heading?.closest('.panel');if(!panel)return;const box=document.createElement('div');box.innerHTML=presetLibrary();panel.insertAdjacentElement('afterend',box.firstElementChild);document.querySelectorAll('[data-use-preset]').forEach(b=>b.onclick=()=>{const select=document.getElementById('planChoice');if(!select)return;select.value=b.dataset.usePreset;document.querySelector('[data-extra="selectplan"]')?.click()})}
  async function injectReorder(){if(document.getElementById('activeWorkoutReorder')||!document.querySelector('[data-action="nextexercise"]'))return;const anchor=document.querySelector('.session-strip')||document.querySelector('.screen');if(!anchor)return;const box=document.createElement('details');box.id='activeWorkoutReorder';box.className='panel workout-reorder';box.innerHTML='<summary><strong>Reorder exercises</strong></summary><p class="muted tiny">Loading exercise order…</p>';anchor.insertAdjacentElement('beforebegin',box);try{const d=await planner('active_session');state.active=d.session;if(!state.active?.day_snapshot?.plan_day_exercises?.length){box.remove();return}renderReorder(box)}catch{box.remove()}}
  function renderReorder(box){const slots=[...(state.active?.day_snapshot?.plan_day_exercises||[])].sort((a,b)=>(a.sort_order??0)-(b.sort_order??0));box.innerHTML=`<summary><strong>Reorder exercises</strong></summary><p class="muted tiny">Machine taken? Move that exercise down for this workout only.</p>${slots.map((s,i)=>`<div class="mini-row"><span><strong>${i+1}. ${esc(s.exercises?.name||'Exercise')}</strong></span><div class="row-actions"><button class="secondary" data-reorder="${i}:-1" ${i===0?'disabled':''}>↑ Up</button><button class="secondary" data-reorder="${i}:1" ${i===slots.length-1?'disabled':''}>↓ Down</button></div></div>`).join('')}`;box.querySelectorAll('[data-reorder]').forEach(b=>b.onclick=async e=>{e.preventDefault();e.stopPropagation();const [i,delta]=b.dataset.reorder.split(':').map(Number),next=i+delta;if(next<0||next>=slots.length)return;[slots[i],slots[next]]=[slots[next],slots[i]];b.disabled=true;try{await planner('reorder_active',{sessionId:state.active.id,orderedSlotIds:slots.map(x=>x.id)});localStorage.setItem('bodysmith-auto-resume','1');location.reload()}catch(err){toast(err.message,true);b.disabled=false}})}
  function autoResume(){if(localStorage.getItem('bodysmith-auto-resume')!=='1')return;const resume=document.querySelector('[data-action="resume"]');if(resume){localStorage.removeItem('bodysmith-auto-resume');resume.click()}}
  function enhance(){if(!token())return;const home=document.querySelector('.dashboard-intro');if(home&&!document.querySelector('.planner-launch.home'))home.insertAdjacentElement('afterend',launchCard('home'));const planTitle=[...document.querySelectorAll('.section-title h1')].find(x=>x.textContent.trim()==='Plan');if(planTitle&&!document.querySelector('.planner-launch.plan'))planTitle.closest('.section-title')?.insertAdjacentElement('afterend',launchCard('plan'));injectPresetLibrary();injectReorder();autoResume();if(!state.loaded&&!state.loading)load()}
  let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}const app=document.getElementById('app');if(app)new MutationObserver(schedule).observe(app,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});else enhance();
  window.BodySmithPlanner={open,refresh:()=>load(true)};
})();