(()=>{
  const TOKEN_KEY='bodysmith-token-v2';
  const API_KEY='sb_publishable_ibEVVafS4THz-16p4euMfg_qjG2WeU2';
  const CORE_URL='https://uuzctytbguqjumwpczfh.supabase.co/functions/v1/bodysmith-api';
  const SESSION_URL='https://uuzctytbguqjumwpczfh.supabase.co/functions/v1/bodysmith-session';
  const token=()=>localStorage.getItem(TOKEN_KEY)||'';
  const cacheKey=()=>token()?`bodysmith-cache-v3-${token().slice(-24)}`:'';
  const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let selectedCalendarDate='',supplementBoot=null,supplementBootAt=0,busy=false;

  function toast(message,error=false){const el=document.getElementById('toast');if(!el){alert(message);return}el.textContent=message;el.className=`show${error?' error':''}`;clearTimeout(el._r213);el._r213=setTimeout(()=>el.className='',3400)}
  function readCache(){try{return JSON.parse(localStorage.getItem(cacheKey())||'null')}catch{return null}}
  function writeCache(data){const key=cacheKey();if(key)try{localStorage.setItem(key,JSON.stringify(data))}catch{}}
  async function post(url,action,payload={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY},body:JSON.stringify({action,...payload,token:token()})});const data=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Error(data.error||`Request failed (${r.status})`);return data}
  const core=(action,payload)=>post(CORE_URL,action,payload),sessionApi=(action,payload)=>post(SESSION_URL,action,payload);

  function formatClock12(value){const m=String(value||'').trim().match(/^([01]\d|2[0-3]):([0-5]\d)$/);if(!m)return String(value||'');const h=Number(m[1]);return `${h%12||12}:${m[2]} ${h>=12?'PM':'AM'}`}
  function parseClock(value){const raw=String(value||'').trim();let m=raw.match(/^([01]?\d|2[0-3]):([0-5]\d)$/);if(m)return `${String(Number(m[1])).padStart(2,'0')}:${m[2]}`;m=raw.toUpperCase().replace(/\./g,'').match(/^(\d{1,2})(?::([0-5]\d))?\s*(AM|PM)$/);if(!m)return null;let h=Number(m[1]);if(h<1||h>12)return null;const minutes=m[2]||'00';if(m[3]==='AM'&&h===12)h=0;if(m[3]==='PM'&&h!==12)h+=12;return `${String(h).padStart(2,'0')}:${minutes}`}
  function parseClockList(value){const parts=String(value||'').split(',').map(x=>x.trim()).filter(Boolean);if(!parts.length)throw Error('Enter at least one supplement time, such as 9:00 AM.');const parsed=parts.map(parseClock);if(parsed.some(x=>!x))throw Error('Use AM/PM times such as 9:00 AM or 8:30 PM.');return [...new Set(parsed)]}
  function formatClockText(root){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes)node.nodeValue=node.nodeValue.replace(/\b([01]\d|2[0-3]):([0-5]\d)\b(?!\s*(?:AM|PM))/gi,(all,h,m)=>formatClock12(`${h}:${m}`))}

  function cleanDeletedSession(sessionId){const c=readCache();if(c){if(c.active?.id===sessionId)c.active=null;if(Array.isArray(c.history))c.history=c.history.filter(h=>h.id!==sessionId);writeCache(c)}localStorage.removeItem('bodysmith-auto-resume')}
  async function deleteWorkout(sessionId,button){if(!sessionId||!confirm('Delete this workout permanently? Its sets and workout metrics will be removed. This cannot be undone.'))return;if(button){button.disabled=true;button.textContent='Deleting…'}try{await sessionApi('delete_session',{sessionId});cleanDeletedSession(sessionId);toast('Workout deleted.');setTimeout(()=>location.reload(),450)}catch(err){toast(err.message||'Could not delete workout.',true);if(button){button.disabled=false;button.textContent='Delete workout'}}}

  function enhanceActiveWorkout(){const title=document.querySelector('.active-title');if(!title||document.querySelector('[data-delete-active213]'))return;const active=readCache()?.active;if(!active?.id)return;const button=document.createElement('button');button.type='button';button.className='danger-213 danger-active-213';button.dataset.deleteActive213=active.id;button.innerHTML='<strong>Delete this workout</strong><span>Started by mistake? Remove it instead of saving a partial workout.</span>';button.onclick=()=>deleteWorkout(active.id,button);const screen=title.closest('.screen'),swap=screen?.querySelector('.swap-panel');if(swap)swap.insertAdjacentElement('afterend',button);else screen?.appendChild(button)}
  function enhanceHistoryRows(){if(![...document.querySelectorAll('.section-title h1')].some(h=>h.textContent.trim()==='Progress'))return;const history=(readCache()?.history||[]).filter(h=>h.status!=='in_progress').slice(0,20);document.querySelectorAll('.history-detail').forEach((detail,index)=>{if(detail.querySelector('[data-delete-history213]'))return;const session=history[index];if(!session?.id)return;const button=document.createElement('button');button.type='button';button.className='danger-213 danger-history-213';button.dataset.deleteHistory213=session.id;button.textContent='Delete workout';button.onclick=e=>{e.preventDefault();e.stopPropagation();deleteWorkout(session.id,button)};detail.appendChild(button)})}
  async function enhanceCalendarDialog(){const dialog=document.querySelector('#calendarDayDetail .calendar-day-dialog');if(!dialog||dialog.dataset.deleteEnhanced213==='1'||!selectedCalendarDate)return;dialog.dataset.deleteEnhanced213='1';try{const data=await core('history',{limit:100});const sessions=(data.history||[]).filter(x=>['completed','abandoned'].includes(x.status)&&localDate(new Date(x.started_at))===selectedCalendarDate);dialog.querySelectorAll('.day-session').forEach((card,index)=>{const session=sessions[index];if(!session?.id)return;const button=document.createElement('button');button.type='button';button.className='danger-213 danger-calendar-213';button.dataset.deleteCalendar213=session.id;button.textContent='Delete workout';button.onclick=()=>deleteWorkout(session.id,button);(card.querySelector('.mini-row')||card).insertAdjacentElement('afterend',button)})}catch(err){console.warn('BodySmith calendar delete enhancement unavailable',err)}}

  async function getSupplementBoot(force=false){if(!force&&supplementBoot&&Date.now()-supplementBootAt<30000)return supplementBoot;supplementBoot=await core('bootstrap');supplementBootAt=Date.now();return supplementBoot}
  const supplementDateLabel=date=>new Date(`${date}T12:00:00`).toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'});
  function matchingDoses(boot,date){const dow=new Date(`${date}T12:00:00`).getDay();return (boot.supplements||[]).filter(s=>s.active&&(s.schedule_days||[]).includes(dow)).flatMap(s=>(s.times||[]).map(time=>({s,time,log:(boot.supplementLogs||[]).find(l=>l.supplement_id===s.id&&l.scheduled_date===date&&l.scheduled_time===time)}))).sort((a,b)=>a.time.localeCompare(b.time))}
  function renderPastSupplements(boot,date){const native=[...document.querySelectorAll('section.panel')].find(p=>p.querySelector('h2')?.textContent.trim()==="Today's checklist");if(native)native.hidden=true;let host=document.getElementById('supplementPastChecklist213');if(!host){host=document.createElement('section');host.id='supplementPastChecklist213';host.className='panel supplement-past-checklist-213';(native||document.querySelector('.supplement-date-panel-213'))?.insertAdjacentElement('afterend',host)}const doses=matchingDoses(boot,date),taken=doses.filter(d=>d.log?.status==='taken').length;host.innerHTML=`<div class="past-checklist-head"><div><span class="eyebrow">PAST DAY</span><h2>${esc(supplementDateLabel(date))}</h2><p class="muted tiny">Record what you actually took that day. This updates adherence without changing today's checklist.</p></div><span class="pill">${taken}/${doses.length} taken</span></div>${doses.length?doses.map(({s,time,log})=>`<article class="dose past-dose-213" data-status="${esc(log?.status||'due')}"><div><strong>${esc(s.name)}</strong><p class="muted">${esc(s.dose)} ${esc(s.unit)} · ${esc(formatClock12(time))}${s.with_food?`<br>${esc(s.with_food)}`:''}</p></div><div class="dose-actions"><button type="button" class="${log?.status==='taken'?'primary':'secondary'}" data-past-dose-213="${s.id}|${time}|taken">Taken</button><button type="button" class="${log?.status==='skipped'?'primary':'secondary'}" data-past-dose-213="${s.id}|${time}|skipped">Skipped</button></div></article>`).join(''):'<p class="muted">No active supplements are scheduled for this day.</p>'}`;host.querySelectorAll('[data-past-dose-213]').forEach(button=>button.onclick=async()=>{const [supplementId,time,status]=button.dataset.pastDose213.split('|');button.disabled=true;try{const result=await core('log_supplement',{supplementId,time,status,date});boot.supplementLogs=(boot.supplementLogs||[]).filter(l=>!(l.supplement_id===supplementId&&l.scheduled_date===date&&l.scheduled_time===time));if(result.log)boot.supplementLogs.push(result.log);renderPastSupplements(boot,date);toast(`Supplement marked ${status} for ${supplementDateLabel(date)}.`)}catch(err){toast(err.message||'Could not save supplement entry.',true);button.disabled=false}});const count=document.querySelector('.section-title span');if(count)count.textContent=`${taken}/${doses.length} taken · ${supplementDateLabel(date)}`}
  async function applySupplementDate(date){const today=localDate(),native=[...document.querySelectorAll('section.panel')].find(p=>p.querySelector('h2')?.textContent.trim()==="Today's checklist"),past=document.getElementById('supplementPastChecklist213'),panel=document.querySelector('.supplement-date-panel-213'),count=document.querySelector('.section-title span');if(date===today){if(native)native.hidden=false;if(past)past.remove();if(count&&panel?.dataset.todayCount)count.textContent=panel.dataset.todayCount;formatClockText(native);return}if(native)native.hidden=true;let loading=past;if(!loading){loading=document.createElement('section');loading.id='supplementPastChecklist213';loading.className='panel supplement-past-checklist-213';(native||panel)?.insertAdjacentElement('afterend',loading)}loading.innerHTML='<p class="muted">Loading supplement history…</p>';try{renderPastSupplements(await getSupplementBoot(true),date)}catch(err){loading.innerHTML=`<p class="muted">${esc(err.message||'Could not load supplement history.')}</p>`}}
  function enhanceSupplementForm(){const input=document.querySelector('#suppForm input[name="times"]');if(!input||input.dataset.ampm213==='1')return;input.dataset.ampm213='1';input.value=String(input.value||'').split(',').map(x=>formatClock12(x.trim())).join(', ');input.placeholder='9:00 AM, 6:00 PM';const label=input.closest('label');if(label)[...label.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE&&/Times/i.test(n.nodeValue||'')).forEach(n=>n.nodeValue='Times (AM/PM, separated by commas)');const hint=document.createElement('span');hint.className='muted tiny ampm-hint-213';hint.textContent='Example: 9:00 AM, 8:30 PM';input.insertAdjacentElement('afterend',hint)}
  function enhanceSupplements(){const heading=[...document.querySelectorAll('.section-title h1')].find(h=>h.textContent.trim()==='Supplements');if(!heading)return;enhanceSupplementForm();const native=[...document.querySelectorAll('section.panel')].find(p=>p.querySelector('h2')?.textContent.trim()==="Today's checklist");formatClockText(native);if(document.querySelector('.supplement-date-panel-213'))return;const panel=document.createElement('section');panel.className='panel supplement-date-panel-213';const today=localDate(),yesterday=localDate(new Date(Date.now()-86400000)),min=localDate(new Date(Date.now()-89*86400000)),count=document.querySelector('.section-title span');panel.dataset.todayCount=count?.textContent||'';panel.innerHTML=`<div><span class="eyebrow">ADHERENCE DATE</span><h3>Record supplements by date</h3><p class="muted tiny">Choose today or a previous day. Use this when you remember later that you took something last night.</p></div><label class="field">Date<input id="supplementLogDate213" type="date" min="${min}" max="${today}" value="${today}"></label><div class="supplement-date-shortcuts-213"><button type="button" class="secondary" data-supp-date-213="${today}">Today</button><button type="button" class="secondary" data-supp-date-213="${yesterday}">Yesterday</button></div>`;(native||heading.closest('.section-title'))?.insertAdjacentElement(native?'beforebegin':'afterend',panel);panel.querySelector('#supplementLogDate213').onchange=e=>applySupplementDate(e.target.value);panel.querySelectorAll('[data-supp-date-213]').forEach(button=>button.onclick=()=>{const input=panel.querySelector('#supplementLogDate213');input.value=button.dataset.suppDate213;applySupplementDate(input.value)})}

  document.addEventListener('click',event=>{const cell=event.target.closest?.('.calendar-day[data-calendar-date]');if(cell)selectedCalendarDate=cell.dataset.calendarDate||''},true);
  document.addEventListener('keydown',event=>{const cell=event.target.closest?.('.calendar-day[data-calendar-date]');if(cell&&(event.key==='Enter'||event.key===' '))selectedCalendarDate=cell.dataset.calendarDate||''},true);
  document.addEventListener('submit',event=>{const form=event.target;if(!(form instanceof HTMLFormElement)||form.id!=='suppForm')return;const input=form.querySelector('input[name="times"]');if(!input)return;try{const canonical=parseClockList(input.value);input.value=canonical.join(', ');setTimeout(()=>{if(input.isConnected)input.value=canonical.map(formatClock12).join(', ')},0)}catch(err){event.preventDefault();event.stopImmediatePropagation();toast(err.message,true)}},true);
  function enhance(){if(busy)return;busy=true;try{enhanceActiveWorkout();enhanceHistoryRows();enhanceCalendarDialog();enhanceSupplements();document.querySelectorAll('.release').forEach(el=>{if(el.textContent!=='v2.13.0')el.textContent='v2.13.0'})}finally{busy=false}}
  let enhanceQueued=false;const scheduleEnhance=()=>{if(enhanceQueued)return;enhanceQueued=true;requestAnimationFrame(()=>{enhanceQueued=false;enhance()})};new MutationObserver(scheduleEnhance).observe(document.body,{childList:true,subtree:true});enhance();
})();