const CACHE='bodysmith-release-2.2.0';
const MEDIA='bodysmith-workout-media-v1';
const SHELL=["./training.js?v=20260914-release22","./", "./index.html", "./styles.css?v=20260914-release22", "./auth-fix.js?v=20260914-release22", "./app.js?v=20260914-release22", "./manifest.webmanifest?v=20260914-release22", "./icon.svg?v=20260914-release22", "./icon-192.png", "./icon-512.png"];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('bodysmith-')&&k!==CACHE&&k!==MEDIA).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data?.type!=='CACHE_WORKOUT'||!Array.isArray(e.data.urls))return;const base=new URL('./media/',self.registration.scope);const urls=[...new Set(e.data.urls.filter(x=>typeof x==='string').map(x=>new URL(x,self.registration.scope).href).filter(x=>x.startsWith(base.href)&&x.endsWith('.webp')))].slice(0,32);e.waitUntil(caches.open(MEDIA).then(c=>Promise.allSettled(urls.map(async url=>{if(!await c.match(url)){const r=await fetch(url);if(r.ok)await c.put(url,r)}}))));});
self.addEventListener('fetch',e=>{
 const url=new URL(e.request.url);if(e.request.method!=='GET'||url.origin!==location.origin)return;
 const media=url.pathname.startsWith(new URL('./media/',self.registration.scope).pathname);
 e.respondWith((async()=>{if(media){const hit=await caches.match(e.request);if(hit)return hit;}try{const r=await fetch(e.request);if(r.ok){const c=await caches.open(media?MEDIA:CACHE);await c.put(e.request,r.clone());}return r}catch{const hit=await caches.match(e.request);if(hit)return hit;if(e.request.mode==='navigate')return await caches.match('./index.html')||new Response('Open BodySmith online once to enable offline workouts.',{status:503});return new Response('',{status:503});}})());
});
self.addEventListener('push',e=>{let n={};try{n=e.data?.json()||{}}catch{}e.waitUntil(self.registration.showNotification(n.title||'BodySmith reminder',{body:n.body||'Open BodySmith to review your reminders.',icon:'./icon-192.png',badge:'./icon-192.png',tag:n.key||'bodysmith-reminder',data:{url:new URL('./',self.registration.scope).href}}));});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil((async()=>{const tabs=await clients.matchAll({type:'window',includeUncontrolled:true});const tab=tabs.find(c=>c.url.startsWith(self.registration.scope));if(tab)return tab.focus();return clients.openWindow(self.registration.scope);})());});
