const CACHE='bodysmith-release-2.0.1';
const SHELL=["./", "./index.html", "./styles.css?v=20260913-release2", "./auth-fix.js?v=20260913-release2", "./app.js?v=20260913-release2", "./manifest.webmanifest?v=20260913-release2", "./icon.svg?v=20260913-release2", "./icon-192.png", "./icon-512.png", "./media/back-extension.webp", "./media/cable-chest-fly.webp", "./media/cable-crunch.webp", "./media/cable-curl.webp", "./media/cable-lateral-raise.webp", "./media/calf-raise.webp", "./media/chest-supported-row.webp", "./media/dumbbell-bench-press.webp", "./media/dumbbell-row.webp", "./media/glute-bridge.webp", "./media/goblet-squat.webp", "./media/hammer-curl.webp", "./media/incline-dumbbell-press.webp", "./media/incline-machine-press.webp", "./media/lateral-raise.webp", "./media/leg-extension.webp", "./media/leg-press-or-squat.webp", "./media/machine-shoulder-press.webp", "./media/neutral-grip-lat-pulldown.webp", "./media/one-arm-cable-row.webp", "./media/plank.webp", "./media/push-up.webp", "./media/rear-delt-fly.webp", "./media/romanian-deadlift.webp", "./media/rope-triceps-pressdown.webp", "./media/seated-cable-row.webp", "./media/seated-leg-curl.webp", "./media/treadmill-walk.webp", "./media/walking-lunge-or-split-squat.webp"];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('bodysmith-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 const url=new URL(e.request.url);if(e.request.method!=='GET'||url.origin!==location.origin)return;
 e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));}return r}).catch(async()=>{const hit=await caches.match(e.request);if(hit)return hit;if(e.request.mode==='navigate')return caches.match('./index.html');return new Response('',{status:503});}));
});
self.addEventListener('push',e=>{let n={};try{n=e.data?.json()||{}}catch{}e.waitUntil(self.registration.showNotification(n.title||'BodySmith reminder',{body:n.body||'Open BodySmith to review your reminders.',icon:'./icon-192.png',badge:'./icon-192.png',tag:n.key||'bodysmith-reminder',data:{url:new URL('./',self.registration.scope).href}}));});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil((async()=>{const tabs=await clients.matchAll({type:'window',includeUncontrolled:true});const tab=tabs.find(c=>c.url.startsWith(self.registration.scope));if(tab)return tab.focus();return clients.openWindow(self.registration.scope);})());});
