const fs=require('fs'),assert=require('assert/strict');
const js=fs.readFileSync('release-213.js','utf8');
const css=fs.readFileSync('release-213.css','utf8');
const edge=fs.readFileSync('supabase/functions/bodysmith-session/index.ts','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const version=fs.readFileSync('release-version.js','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
for(const term of ['Delete this workout','Delete workout','delete_session','supplementLogDate213','Yesterday','AM/PM','formatClock12','parseClockList','log_supplement'])assert.ok(js.includes(term),term);
for(const term of ['danger-213','supplement-date-panel-213','supplement-past-checklist-213'])assert.ok(css.includes(term),term);
for(const term of ['delete_session','workout_sessions','user_id','app_sessions','token_hash'])assert.ok(edge.includes(term),term);
assert.ok(html.includes('release-213.css?v=20260917-release213'));
assert.ok(html.includes('release-213.js?v=20260918-release214'));
assert.ok(sw.includes('bodysmith-release-2.14.0-release214'));
assert.ok(sw.includes('release-213.js?v=20260917-release213'));
assert.ok(sw.includes('release-213.css?v=20260917-release213'));
assert.ok(version.includes("VERSION='v2.14.0'"));
assert.equal(pkg.version,'2.14.0');
console.log('PASS v2.13 workout deletion, calendar delete controls, AM/PM supplement times and past-date adherence logging');