import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';
const URL='https://uuzctytbguqjumwpczfh.supabase.co/functions/v1/bodysmith-api';
async function api(action,payload={},token='',status=200){const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload,token}),signal:AbortSignal.timeout(30000)});const d=await r.json();assert.equal(r.status,status,action+': '+JSON.stringify(d));return d}
const tokens=[];
try{
 const account=await api('register',{username:'bodysmith_qa_'+randomBytes(6).toString('hex'),password:randomBytes(24).toString('base64url'),displayName:'Session QA',qaMode:true},'',201);tokens.push(account.token);const token=account.token;
 let b=await api('bootstrap',{},token);assert.ok(b.exercises.filter(x=>!x.owner_id&&!x.is_legacy).length>=120);
 const names=['Barbell Bench Press','Incline Barbell Bench Press','Decline Barbell Bench Press'];const ex=names.map(n=>b.exercises.find(x=>x.name===n));assert.ok(ex.every(Boolean));
 const plan={name:'QA Chest Plan',plan_days:[{name:'Chest Day',plan_day_exercises:ex.map((e,i)=>({sort_order:i,exercises:e,target_sets:3,min_reps:8,max_reps:12,target_rpe:'7–8',rest_seconds:90,duration_minutes:0}))}]};
 const saved=await api('save_plan',{plan},token,201);await api('select_plan',{planId:saved.plan.id},token);const day=saved.plan.plan_days[0];let start=await api('start_session',{planDayId:day.id},token,201);const sid=start.session.id;
 const payload={sessionId:sid,exerciseId:ex[0].id,setNumber:1,weight:225,reps:8,rpe:8,units:'lb',loadBasis:'total',loadMultiplier:1};const original=(await api('save_set',payload,token)).set;
 const edited=(await api('save_set',{...payload,weight:215,notes:'Corrected'},token)).set;assert.equal(edited.id,original.id);assert.equal(edited.logged_at,original.logged_at);assert.equal(edited.weight,215);
 await api('set_targets',{sessionId:sid,slotId:day.plan_day_exercises[0].id,targetSets:4},token);await api('save_set',{...payload,setNumber:4},token);b=await api('bootstrap',{},token);assert.equal(b.activeSession.day_snapshot.plan_day_exercises[0].target_sets,4);assert.equal(b.plan.plan_days[0].plan_day_exercises[0].target_sets,3);
 await api('complete_session',{sessionId:sid},token);const before=(await api('history',{},token)).history[0];await api('save_set',{...payload,weight:205},token);await api('save_set',{...payload,setNumber:2,weight:195},token);await api('delete_set',{sessionId:sid,exerciseId:ex[0].id,setNumber:4},token);await api('session_notes',{sessionId:sid,notes:'Historical correction'},token);const after=(await api('history',{},token)).history[0];assert.equal(after.started_at,before.started_at);assert.equal(after.completed_at,before.completed_at);assert.equal(after.sets.length,2);assert.equal(after.sets.find(x=>x.set_number===1).weight,205);
 const other=await api('register',{username:'bodysmith_qa_'+randomBytes(6).toString('hex'),password:randomBytes(24).toString('base64url'),displayName:'Isolation QA',qaMode:true},'',201);tokens.push(other.token);
 await api('delete_set',{sessionId:sid,exerciseId:ex[0].id,setNumber:1},other.token,404);await api('save_set',payload,other.token,404);
 start=await api('start_session',{planDayId:day.id},token,201);await api('save_set',{...payload,sessionId:start.session.id},token);await api('abandon_session',{sessionId:start.session.id},token);const custom=await api('start_custom_session',{day:plan.plan_days[0]},token,201);assert.equal(custom.session.plan_day_id,null);assert.equal(custom.session.day_snapshot.plan_day_exercises.length,3);await api('abandon_session',{sessionId:custom.session.id},token);
 b=await api('bootstrap',{},token);assert.equal(b.activeSession,null);assert.equal(b.history.filter(h=>h.status==='completed').length,1);assert.equal(b.history.filter(h=>h.status==='abandoned').length,2);
 console.log('PASS expanded catalog, three-bench custom plan, set correction without duplicate, extra sets and reload, historical add/edit/delete, timestamps, isolation, partial session, custom session, active session release');
}finally{let failure;for(const token of tokens){try{await api('cleanup_qa',{},token)}catch(e){failure=e}}if(failure)throw failure;console.log('PASS all temporary QA accounts cleaned up')}
