import json,re
from pathlib import Path
# Catalog metadata is authored here; IDs are resolved by slug in additive migrations.
groups={
'flat-press':('Chest',['Triceps','Anterior deltoids'],'Upper body','Horizontal push',90,180,'Keep wrists stacked above elbows.',['Bouncing off the chest','Flaring elbows excessively']),
'incline-press':('Chest',['Anterior deltoids','Triceps'],'Upper body','Incline push',90,180,'Press upward without shrugging.',['Using an overly steep bench','Lifting hips off the pad']),
'decline-press':('Chest',['Triceps','Anterior deltoids'],'Upper body','Decline push',90,180,'Keep shoulders supported and wrists stacked.',['Unsecured legs','Bouncing the load']),
'chest-fly':('Chest',['Anterior deltoids'],'Upper body','Horizontal adduction',45,90,'Keep a soft, fixed elbow bend.',['Turning the fly into a press','Overstretching behind the torso']),
'dip':('Chest',['Triceps','Anterior deltoids'],'Upper body','Dip',90,150,'Use a comfortable shoulder range.',['Dropping too deep','Shrugging at the bottom']),
'vertical-pull':('Back',['Biceps','Lower trapezius'],'Upper body','Vertical pull',90,150,'Lead with elbows; keep the rib cage controlled.',['Pulling behind the neck','Swinging the torso']),
'straight-pull':('Back',['Triceps long head','Abdominals'],'Upper body','Shoulder extension',45,90,'Move at the shoulders with almost-straight arms.',['Bending elbows into a pressdown','Arching the lower back']),
'row':('Back',['Biceps','Rear deltoids'],'Upper body','Horizontal pull',90,150,'Draw elbows back without shrugging.',['Jerking the weight','Losing a stable torso']),
'overhead-press':('Shoulders',['Triceps','Upper chest'],'Upper body','Vertical push',90,180,'Keep ribs stacked over the pelvis.',['Excessive lower-back arch','Pressing behind the neck']),
'lateral-raise':('Shoulders',['Supraspinatus','Upper trapezius'],'Upper body','Shoulder abduction',45,90,'Lead outward with elbows and relaxed traps.',['Swinging the torso','Raising far above shoulder height']),
'front-raise':('Shoulders',['Upper chest'],'Upper body','Shoulder flexion',45,90,'Raise only to about shoulder level.',['Leaning backward','Using momentum']),
'rear-delt':('Shoulders',['Rhomboids','Middle trapezius'],'Upper body','Horizontal abduction',45,90,'Open the arms with a soft elbow bend.',['Shrugging','Throwing the weight']),
'curl':('Biceps',['Brachialis','Forearms'],'Upper body','Elbow flexion',45,90,'Keep upper arms still as elbows bend.',['Swinging the shoulders','Bending wrists backward']),
'hammer-curl':('Biceps',['Brachialis','Brachioradialis'],'Upper body','Neutral-grip elbow flexion',45,90,'Keep palms facing inward.',['Swinging from the hips','Letting elbows drift forward']),
'pressdown':('Triceps',[],'Upper body','Elbow extension',45,90,'Keep elbows beside your ribs.',['Moving the shoulders','Leaning body weight onto the handle']),
'overhead-extension':('Triceps',[],'Upper body','Overhead elbow extension',60,90,'Keep ribs down and upper arms steady.',['Flaring elbows excessively','Arching the lower back']),
'lying-extension':('Triceps',[],'Upper body','Lying elbow extension',60,90,'Bend at the elbows with controlled range.',['Dropping weight toward the face','Turning the movement into a press']),
'knee-dominant':('Quads',['Glutes','Adductors'],'Lower body','Squat',120,180,'Track knees in line with toes.',['Heels lifting','Knees collapsing inward']),
'leg-press':('Quads',['Glutes','Adductors'],'Lower body','Leg press',90,180,'Keep hips and lower back on the pad.',['Pelvis curling off the pad','Forcefully locking knees']),
'lunge':('Quads',['Glutes','Adductors'],'Lower body','Lunge',90,150,'Push through the whole front foot.',['Losing balance','Front knee collapsing inward']),
'knee-extension':('Quads',[],'Lower body','Knee extension',60,90,'Extend smoothly without kicking.',['Swinging the torso','Misaligning knee and machine pivot']),
'hip-extension':('Glutes',['Hamstrings'],'Lower body','Hip extension',90,150,'Finish with glutes, not a lower-back arch.',['Overextending the spine','Driving through the toes']),
'glute-isolation':('Glutes',['Hamstrings'],'Lower body','Isolated hip extension',45,90,'Keep hips square and range controlled.',['Rotating the pelvis','Arching the lower back']),
'abduction':('Glutes',['Tensor fasciae latae'],'Lower body','Hip abduction',45,90,'Open from the hips with a still torso.',['Bouncing the pads','Twisting the torso']),
'hinge':('Hamstrings',['Glutes','Spinal erectors'],'Lower body','Hip hinge',120,180,'Push hips backward and keep load close.',['Rounding the back','Turning a hinge into a squat']),
'deadlift':('Posterior chain',['Quads','Back','Forearms'],'Full body','Deadlift',120,240,'Brace before lifting; push the floor away.',['Jerking slack out of the bar','Rounding under load']),
'leg-curl':('Hamstrings',['Gastrocnemius'],'Lower body','Knee flexion',60,90,'Curl without lifting hips off the pad.',['Arching the back','Letting the stack slam']),
'back-extension':('Posterior chain',['Glutes','Hamstrings'],'Lower body','Hip hinge',60,120,'Hinge at the hips and stop at a straight body line.',['Hyperextending at the top','Rounding and bouncing']),
'calf':('Calves',[],'Lower body','Plantar flexion',45,90,'Pause at the top and lower slowly.',['Bouncing','Rolling onto the outside edge of the foot']),
'core-flexion':('Abs',['Obliques'],'Core','Trunk flexion',45,90,'Curl ribs toward pelvis; breathe out.',['Pulling on the neck','Using hip momentum']),
'leg-raise':('Abs',['Hip flexors'],'Core','Posterior pelvic tilt',45,90,'Curl the pelvis without swinging.',['Arching the lower back','Swinging the legs']),
'brace':('Abs',['Glutes','Shoulders'],'Core','Anti-extension',45,90,'Brace and keep breathing.',['Sagging hips','Holding the breath']),
'side-brace':('Obliques',['Glute medius','Shoulders'],'Core','Anti-lateral flexion',45,90,'Keep shoulders, hips and ankles aligned.',['Hips sagging','Rotating forward']),
'anti-rotation':('Obliques',['Abs','Glutes'],'Core','Anti-rotation',45,90,'Keep chest and hips facing forward.',['Rotating toward the cable','Leaning sideways']),
'rotation':('Obliques',['Abs'],'Core','Controlled rotation',45,90,'Rotate under control through a comfortable range.',['Jerking through the low back','Using more weight than you can control']),
'cardio':('Cardio',['Legs'],'Full body','Cardio',0,60,'Choose a pace you can sustain with control.',['Starting too fast','Ignoring equipment stop controls'])
}
# name | slug | equipment | group | setup | movement | aliases
rows='''
Dumbbell Bench Press|dumbbell-bench-press|Dumbbells|flat-press|Lie on a flat bench with feet planted and dumbbells beside the chest, palms forward.|Press dumbbells over the chest; lower until upper arms reach a comfortable depth.|flat dumbbell press,db bench
Incline Machine Press|incline-machine-press|Selectorized machine|incline-press|Adjust the angled seat so handles line up with the upper chest; keep back against the pad.|Press handles forward and upward; return with control.|incline chest machine
Machine Shoulder Press|machine-shoulder-press|Selectorized machine|overhead-press|Adjust seat so handles begin near shoulder height, feet flat and back supported.|Press overhead without locking hard; lower to the starting handle position.|shoulder press machine
Cable Chest Fly|cable-chest-fly|Cable|chest-fly|Set two pulleys at chest height. Stand between the towers in a split stance with one handle in each hand.|Bring hands together in front of the chest; reopen along the same arc.|cable crossover,mid cable fly
Cable Lateral Raise|cable-lateral-raise|Cable|lateral-raise|Stand beside a cable tower with its pulley at the lowest position. Hold the handle in the farther hand, cable running from that pulley across your front.|Raise the working arm out to shoulder level; lower toward the opposite hip.|single arm cable lateral
Rope Triceps Pressdown|rope-triceps-pressdown|Cable|pressdown|Attach a rope to a high pulley. Face the tower and hold both rope ends with elbows tucked.|Extend elbows downward; separate rope ends slightly near thighs, then return.|rope pushdown,triceps rope
Treadmill Walk|treadmill-walk|Treadmill|cardio|Stand on the side rails, attach the safety clip, start the belt slowly and step onto it.|Walk upright with natural arm swing and steady steps.|treadmill walking,walking
Neutral-Grip Lat Pulldown|neutral-grip-lat-pulldown|Cable|vertical-pull|Sit with thighs secured beneath pads. Hold parallel handles with palms facing each other.|Pull handles to upper chest with elbows moving down; return overhead with control.|neutral pulldown,parallel grip lat pulldown
Neutral-Grip Pulldown|neutral-grip-pulldown|Cable|vertical-pull|Sit with thighs secured and hold parallel overhead handles.|Draw elbows toward your sides; let arms extend overhead slowly.|neutral pulldown legacy
Seated Cable Row|seated-cable-row|Cable|row|Sit facing a low cable pulley with feet on the supports and a neutral-grip handle in both hands.|Pull the handle toward lower ribs; extend arms while keeping torso steady.|close grip cable row,low row
Chest-Supported Row|chest-supported-row|Selectorized machine|row|Adjust the chest pad so both feet are supported and handles are reachable without lifting the chest.|Pull elbows behind the torso; return arms forward against the chest pad.|chest supported machine row,machine row
One-Arm Cable Row|one-arm-cable-row|Cable|row|Face a cable pulley set around waist height in a stable split stance, one handle in one hand.|Draw the elbow toward the hip without twisting; extend the arm.|single arm cable row
Rear Delt Fly|rear-delt-fly|Selectorized machine|rear-delt|Face the chest pad of a reverse pec-deck machine with handles at shoulder level.|Open both arms outward and back; return slowly while chest stays supported.|reverse pec deck,rear delt machine,reverse fly machine
Cable Curl|cable-curl|Cable|curl|Attach a straight bar to a low pulley and stand facing the tower, palms upward.|Curl the bar toward shoulders with elbows still; lower fully under control.|standing cable biceps curl
Hammer Curl|hammer-curl|Dumbbells|hammer-curl|Stand with dumbbells at your sides, palms facing inward.|Curl both weights toward shoulders without turning palms; lower slowly.|neutral grip dumbbell curl
Back Extension|back-extension|Back extension bench|back-extension|Set the hip pad below the hip crease and secure feet under the ankle supports.|Fold at the hips; raise the torso only until it aligns with the legs.|45 degree back extension,hyperextension
Romanian Deadlift|romanian-deadlift|Barbell|hinge|Stand holding a barbell against thighs with an overhand grip and knees softly bent.|Push hips backward while bar tracks down the legs; stand by extending hips.|barbell rdl,rdl
Leg Press or Squat|leg-press-or-squat|Leg press machine|leg-press|Legacy plan choice. The illustration shows a leg press: sit with hips and back against the pad and feet on the platform.|Lower the sled only while the pelvis stays on the pad; press through the whole foot. Choose a specific squat separately in new plans.|legacy leg choice
Seated Leg Curl|seated-leg-curl|Selectorized machine|leg-curl|Align knees with the machine pivot, secure thigh pad and place lower legs on the roller.|Bend knees to draw heels beneath the seat; extend slowly.|seated hamstring curl
Leg Extension|leg-extension|Selectorized machine|knee-extension|Sit with knees aligned to the pivot and the roller above the front of the ankles.|Straighten knees smoothly; lower until knees bend comfortably.|quad extension,knee extension
Calf Raise|calf-raise|Calf raise machine|calf|Set shoulder pads and place balls of feet on the standing machine platform, heels free.|Rise onto the forefoot; lower heels through a comfortable range.|standing machine calf raise
Walking Lunge or Split Squat|walking-lunge-or-split-squat|Dumbbells|lunge|Legacy plan choice. The illustration shows a stationary split squat: stand in a staggered stance with both feet on the floor.|Lower the back knee toward the floor; press through the front foot. Choose walking lunges separately in new plans.|legacy lunge choice,stationary split squat
Cable Crunch|cable-crunch|Cable|core-flexion|Attach a rope to a high pulley. Kneel facing the tower, rope held beside the head, hips steady.|Curl ribs toward pelvis; return without pulling with the arms.|kneeling cable crunch
Incline Dumbbell Press|incline-dumbbell-press|Dumbbells|incline-press|Set bench to about 30 degrees. Sit back with feet planted and dumbbells beside upper chest.|Press upward over shoulders; lower along a controlled arc.|incline dumbbell bench press,incline db press
Lateral Raise|lateral-raise|Dumbbells|lateral-raise|Stand with dumbbells beside thighs and elbows softly bent.|Lift arms slightly forward of your sides to shoulder level; lower slowly.|dumbbell lateral raise,side raise,db lateral
Goblet Squat|goblet-squat|Dumbbell|knee-dominant|Hold one dumbbell vertically at chest level and set feet around shoulder width.|Sit down between the hips; stand while keeping heels grounded.|dumbbell goblet squat
One-Arm Dumbbell Row|dumbbell-row|Dumbbell and bench|row|Support one hand and knee on a flat bench; hold a dumbbell in the other hand with hips level.|Pull the elbow toward your hip; lower without rotating the torso.|dumbbell row,db row,one arm row
Push-Up|push-up|Bodyweight|flat-press|Place hands slightly wider than shoulders and extend legs into a straight-body plank.|Lower chest between hands; press back up as one unit.|press up,pushup
Glute Bridge|glute-bridge|Bodyweight|hip-extension|Lie on your back with knees bent and feet flat, arms on the floor.|Drive through feet to lift hips; pause with ribs down and lower.|floor bridge
Plank|plank|Bodyweight|brace|Place elbows beneath shoulders, forearms on floor, legs extended and toes grounded.|Hold a straight-body position while taking steady breaths.|front plank,forearm plank
Barbell Bench Press|barbell-bench-press|Barbell|flat-press|Lie on a flat bench with feet planted. Grip just outside shoulder width. Use a spotter or correctly positioned safety arms.|Unrack over shoulders, lower to mid-chest with forearms vertical, then press up and slightly back.|bench press,flat bench,barbell chest press,flat barbell press
Incline Barbell Bench Press|incline-barbell-bench-press|Barbell|incline-press|Set a bench about 30 degrees with head higher than hips. Grip just outside shoulders and set safeties or use a spotter.|Lower the bar to upper chest; press vertically over shoulders without lifting hips.|incline bench,incline barbell press,incline chest press
Decline Barbell Bench Press|decline-barbell-bench-press|Barbell|decline-press|Use a shallow decline bench with head below hips and legs secured under the rollers. Set safeties and use a spotter.|Lower to the lower chest; press back over shoulders, keeping body secured.|decline bench,decline barbell press
Smith Machine Bench Press|smith-machine-bench-press|Smith machine|flat-press|Position a flat bench under the Smith bar so its track meets the mid-chest. Set safety stops just below your intended range.|Unhook the bar, lower to chest level and press along the rails. Rehook only at the top.|smith flat bench,smith chest press
Smith Machine Incline Press|smith-machine-incline-press|Smith machine|incline-press|Set a roughly 30-degree bench beneath the Smith bar so it reaches upper chest. Set safety stops.|Unhook, lower with elbows beneath the bar, then press along the rails.|smith incline bench
Smith Machine Decline Press|smith-machine-decline-press|Smith machine|decline-press|Secure legs on a shallow decline bench under the Smith bar. Position the track at lower chest and set stops.|Unhook and lower the bar with control; press up along the rails.|smith decline bench
Decline Dumbbell Press|decline-dumbbell-press|Dumbbells|decline-press|Secure legs on a shallow decline bench, head lower than hips. Get the dumbbells into position safely, with assistance if needed.|Lower beside lower chest; press over shoulders without clashing the weights.|decline db bench
Flat Machine Chest Press|flat-machine-chest-press|Selectorized machine|flat-press|Set the seat so handles align with mid-chest and keep feet flat and back against the pad.|Press handles forward; return until elbows reach a comfortable depth.|machine chest press,seated chest press
Plate-Loaded Chest Press|plate-loaded-chest-press|Plate-loaded machine|flat-press|Load both machine arms evenly. Adjust seat so handles start at mid-chest and back is supported.|Press the levers forward; return smoothly without bouncing against stops.|hammer strength chest press,iso lateral chest press
Incline Plate-Loaded Chest Press|incline-plate-loaded-chest-press|Plate-loaded machine|incline-press|Load both sides evenly and adjust seat so the inclined lever handles begin at upper chest.|Press forward and upward along the machine arc; lower under control.|hammer strength incline press
Chest Dip|chest-dip|Parallel bars|dip|Support yourself on parallel bars with shoulders down and a slight forward torso lean.|Bend elbows to a comfortable depth, then press back to the top without swinging.|parallel bar dip,pectoral dip
Pec Deck|pec-deck|Selectorized machine|chest-fly|Sit with back against the pad and adjust handles or forearm pads around chest height.|Bring arms together in front of the chest; open only to a comfortable stretch.|chest fly machine,butterfly machine
Low-to-High Cable Fly|low-to-high-cable-fly|Cable|chest-fly|Set both machine pulleys low and stand between the towers in a split stance, cables running from the visible low pulleys to the handles.|Sweep hands upward and inward toward upper chest; return along the same arc.|low cable fly,upper chest cable fly
High-to-Low Cable Fly|high-to-low-cable-fly|Cable|chest-fly|Set both machine pulleys above shoulder height; hold handles and step forward between the towers.|Sweep hands down and inward toward the lower chest; return smoothly.|high cable crossover,lower chest fly
Single-Arm Cable Fly|single-arm-cable-fly|Cable|chest-fly|Stand side-on to a chest-height machine pulley with one handle and a stable split stance.|Sweep the working hand across the chest without rotating your torso; return.|one arm cable fly
Dumbbell Chest Fly|dumbbell-chest-fly|Dumbbells|chest-fly|Lie on a flat bench with dumbbells above chest, palms facing and elbows softly bent.|Open arms in a wide arc to a comfortable depth; bring them together above chest.|flat dumbbell fly,db fly
Incline Push-Up|incline-push-up|Bodyweight and bench|flat-press|Place hands on a stable elevated bench or bar and walk feet back into a straight body line.|Lower chest toward the support; press away without bending at the hips.|elevated pushup,bench push up
Decline Push-Up|decline-push-up|Bodyweight and bench|incline-press|Place toes on a stable low bench and hands on floor, maintaining a braced straight body.|Lower chest toward floor; press up without letting the lower back sag.|feet elevated pushup
Pull-Up|pull-up|Pull-up bar|vertical-pull|Hang from a secure bar with an overhand grip just wider than shoulders; brace the torso.|Pull until chin clears the bar without craning; lower to a controlled hang.|overhand pullup,conventional pull up
Assisted Pull-Up|assisted-pull-up|Assisted pull-up machine|vertical-pull|Select assistance, step onto the machine and place knees or feet on the moving support as designed.|Pull upward with elbows down; lower slowly while staying on the support.|assisted chin pull machine
Chin-Up|chin-up|Pull-up bar|vertical-pull|Hang from a secure bar with palms facing you and hands around shoulder width.|Pull chest toward the bar; lower without swinging or dropping.|chinup,underhand pull up
Neutral-Grip Pull-Up|neutral-grip-pull-up|Pull-up bar|vertical-pull|Use parallel overhead handles so palms face each other and brace the trunk.|Pull elbows toward sides until chin passes handle height; lower under control.|parallel grip pullup
Wide-Grip Lat Pulldown|wide-grip-lat-pulldown|Cable|vertical-pull|Secure thighs beneath pads and take an overhand grip wider than shoulders on the overhead bar.|Pull to upper chest in front of your face; return overhead slowly.|wide pulldown,lat pull down
Close-Grip Lat Pulldown|close-grip-lat-pulldown|Cable|vertical-pull|Attach a close-grip V handle to the high pulley, sit and secure thighs beneath pads.|Draw the handle to upper chest; extend arms overhead with control.|v bar pulldown,close grip pulldown
Single-Arm Lat Pulldown|single-arm-lat-pulldown|Cable|vertical-pull|Kneel or sit facing a high machine pulley with a single handle in one hand.|Pull elbow down toward the ribs; return the arm overhead without twisting.|one arm pulldown
Straight-Arm Pulldown|straight-arm-pulldown|Cable|straight-pull|Attach a straight bar to a high pulley. Face the tower, hinge slightly and hold the bar with nearly straight arms.|Sweep the bar down toward thighs using the shoulders; return overhead to a comfortable stretch.|cable pullover,lat prayer
Barbell Row|barbell-row|Barbell|row|Hold a barbell with overhand grip. Hinge forward with knees soft and a braced neutral back.|Row toward lower ribs; lower while preserving the torso angle.|bent over barbell row,bent over row
Pendlay Row|pendlay-row|Barbell|row|Set a barbell on the floor. Hinge until torso is nearly horizontal while maintaining a neutral back; bend knees as needed.|Row from a dead stop to lower chest, then return the bar to the floor each rep.|dead stop row
T-Bar Row|t-bar-row|T-bar row machine|row|Stand on the foot platform of a landmine-style T-bar station, hinge and grip the close handles.|Row the loaded lever toward the abdomen; lower without rounding.|tbar row,close grip t bar
Landmine Row|landmine-row|Landmine barbell|row|Secure one barbell end in a landmine pivot. Straddle the bar and use a V handle beneath the free end, knees soft.|Row the free end toward lower ribs; lower with torso steady.|meadows landmine two arm row
Chest-Supported Dumbbell Row|chest-supported-dumbbell-row|Dumbbells and bench|row|Lie chest-down on a bench inclined about 30–45 degrees with feet planted and dumbbells hanging.|Draw elbows back beside the body; lower without lifting the chest.|incline dumbbell row,seal incline row
Wide-Grip Seated Cable Row|wide-grip-seated-cable-row|Cable|row|Sit at a low pulley with feet supported and hold a wide straight bar overhand.|Pull toward upper abdomen with elbows out moderately; return without rocking.|wide cable row
Machine High Row|machine-high-row|Plate-loaded machine|row|Adjust seat and chest pad so overhead diagonal handles are reachable and feet are supported.|Pull the levers down and back toward upper ribs; extend along their arc.|hammer strength high row
Standing Barbell Overhead Press|standing-barbell-overhead-press|Barbell|overhead-press|Stand with feet hip-width, bar at upper chest and hands just outside shoulders.|Press overhead, moving head slightly out of the bar path; finish stacked and lower.|overhead press,military press,ohp,standing press
Seated Barbell Shoulder Press|seated-barbell-shoulder-press|Barbell|overhead-press|Use a nearly upright bench in a rack with safeties. Grip just outside shoulders with bar in front of the face.|Lower toward upper chest as comfortable; press overhead without arching.|seated military press
Dumbbell Shoulder Press|dumbbell-shoulder-press|Dumbbells|overhead-press|Sit on a nearly upright bench with dumbbells beside shoulders and forearms vertical.|Press overhead in a comfortable path; lower to shoulder height.|seated dumbbell press,db shoulder press
Arnold Press|arnold-press|Dumbbells|overhead-press|Sit upright with dumbbells in front of shoulders, palms facing you and elbows bent.|Rotate palms forward as you press overhead; reverse the rotation while lowering.|arnold shoulder press
Smith Machine Shoulder Press|smith-machine-shoulder-press|Smith machine|overhead-press|Place a nearly upright bench under the Smith bar, track in front of your face, with safety stops set.|Press from upper-chest height along the rails; lower under control.|smith shoulder press
Machine Lateral Raise|machine-lateral-raise|Selectorized machine|lateral-raise|Adjust seat with shoulders aligned to the machine pivot and upper arms beneath pads.|Lift elbows outward to shoulder height; lower slowly.|lateral raise machine
Leaning Dumbbell Lateral Raise|leaning-dumbbell-lateral-raise|Dumbbell|lateral-raise|Hold a stable upright with the free hand and lean slightly away, dumbbell in the outside hand.|Raise the working arm out to shoulder level; return without swinging.|lean away lateral raise
Dumbbell Front Raise|dumbbell-front-raise|Dumbbells|front-raise|Stand with dumbbells in front of thighs, palms facing down and elbows soft.|Raise weights forward to shoulder height; lower under control.|front delt raise
Cable Front Raise|cable-front-raise|Cable|front-raise|Face away from a low machine pulley with a rope passing between the legs from the actual pulley.|Raise hands forward to shoulder height; lower without leaning back.|rope front raise
Dumbbell Rear-Delt Fly|dumbbell-rear-delt-fly|Dumbbells|rear-delt|Hinge at hips with a braced back and dumbbells beneath shoulders, elbows softly bent.|Open arms out to the sides; lower without changing torso position.|bent over reverse fly,rear delt dumbbell fly
Face Pull|face-pull|Cable|rear-delt|Attach a rope to a machine pulley around eye level. Step back and hold both ends with arms forward.|Pull rope toward forehead while separating hands beside the head; return.|cable face pull
Cable Upright Row|cable-upright-row|Cable|lateral-raise|Face a low pulley using a wide straight-bar grip, shoulders relaxed.|Lift elbows outward only to a comfortable height below shoulder level; lower.|wide grip upright row
Barbell Curl|barbell-curl|Barbell|curl|Stand holding a straight bar with an underhand shoulder-width grip, elbows beside torso.|Curl toward shoulders without moving upper arms; lower slowly.|standing barbell biceps curl
EZ-Bar Curl|ez-bar-curl|EZ-bar|curl|Hold the angled grips of an EZ bar with palms mostly upward, elbows beside torso.|Curl toward shoulders; lower while keeping wrists aligned.|ez curl,easy bar curl
Dumbbell Curl|dumbbell-curl|Dumbbells|curl|Stand with one dumbbell in each hand, palms forward and arms by your sides.|Curl both weights toward shoulders; lower with elbows steady.|standing db biceps curl
Alternating Dumbbell Curl|alternating-dumbbell-curl|Dumbbells|curl|Stand with dumbbells at sides, elbows close to ribs.|Curl one weight while turning palm upward, lower it, then repeat on the other side.|alternating curl,alternate db curl
Incline Dumbbell Curl|incline-dumbbell-curl|Dumbbells and bench|curl|Sit back on a bench inclined about 45–60 degrees, arms hanging behind the torso line.|Curl with upper arms still; lower to a comfortable stretch without forcing shoulders back.|incline curl
Cross-Body Hammer Curl|cross-body-hammer-curl|Dumbbells|hammer-curl|Stand holding dumbbells with neutral palms, arms beside torso.|Curl one weight diagonally toward the opposite chest while keeping elbow close; lower and alternate.|pinwheel curl
Bayesian Cable Curl|bayesian-cable-curl|Cable|curl|Stand facing away from a low machine pulley, handle in one hand with upper arm slightly behind torso, cable visibly connected behind you.|Bend the elbow to curl forward without moving the upper arm; extend slowly.|behind body cable curl
Preacher Curl|preacher-curl|EZ-bar and preacher bench|curl|Set the preacher pad under upper arms with armpits near its top edge; hold an EZ bar palms up.|Curl the bar up; lower slowly without forcing elbows into a locked stretch.|ez preacher curl,preacher bench curl
Machine Preacher Curl|machine-preacher-curl|Selectorized machine|curl|Adjust seat so upper arms rest fully on the preacher pad and elbows align with the pivot.|Curl the handles; extend slowly without lifting arms off the pad.|biceps curl machine
Concentration Curl|concentration-curl|Dumbbell|curl|Sit with feet apart and brace the working upper arm against the inside of the same-side thigh.|Curl toward the shoulder; lower without moving the upper arm.|seated concentration biceps curl
Straight-Bar Triceps Pressdown|straight-bar-triceps-pressdown|Cable|pressdown|Attach a straight bar to a high machine pulley and hold it overhand with elbows at your sides.|Extend elbows until arms are straight; return without lifting upper arms.|straight bar pushdown,triceps pushdown
Reverse-Grip Triceps Pressdown|reverse-grip-triceps-pressdown|Cable|pressdown|Attach a bar to a high pulley and use an underhand grip with a manageable load.|Extend elbows down while wrists stay straight; bend elbows slowly to return.|underhand pushdown
Single-Arm Cable Pressdown|single-arm-cable-pressdown|Cable|pressdown|Face a high machine pulley and hold one handle with the elbow beside the torso.|Straighten the elbow toward the thigh; return without rotating the shoulder.|one arm triceps pushdown
Overhead Rope Triceps Extension|overhead-rope-triceps-extension|Cable|overhead-extension|Attach a rope to a low machine pulley behind you. Face away, hold rope above the head and set a staggered stance.|Bend elbows to lower hands behind head; extend elbows overhead, keeping cable connected to the pulley behind.|overhead rope extension,cable overhead triceps
Dumbbell Overhead Triceps Extension|dumbbell-overhead-triceps-extension|Dumbbell|overhead-extension|Sit upright and support one dumbbell with both hands above your head.|Bend elbows to lower the weight behind head; extend without arching the back.|overhead dumbbell extension,french press dumbbell
Barbell Skull Crusher|barbell-skull-crusher|Barbell|lying-extension|Lie on a flat bench with a straight bar held above shoulders in a shoulder-width overhand grip.|Bend elbows to lower bar just behind forehead; extend slowly back up.|skull crusher,lying triceps extension
EZ-Bar Skull Crusher|ez-bar-skull-crusher|EZ-bar|lying-extension|Lie on a flat bench holding the angled EZ-bar grips above shoulders.|Lower the bar just behind forehead by bending elbows; extend with upper arms steady.|ez lying triceps extension
Close-Grip Bench Press|close-grip-bench-press|Barbell|flat-press|Set up on a flat bench with hands around shoulder width, not touching. Use a spotter or safety arms.|Lower to lower chest with elbows near torso; press back over shoulders.|close grip barbell bench,triceps bench
Machine Dip|machine-dip|Selectorized machine|pressdown|Sit against the back pad, feet supported, hands on the side handles and elbows bent.|Press handles down by extending elbows; return smoothly.|seated dip machine,triceps dip machine
Bench Dip|bench-dip|Bodyweight and bench|pressdown|Place hands beside hips on a stable bench, feet on the floor and knees bent. Keep hips close to the bench.|Bend elbows through a shallow comfortable range; press back up. Skip if shoulder position is uncomfortable.|triceps bench dip
Back Squat|back-squat|Barbell|knee-dominant|Set a bar on upper traps in a rack with safety arms. Brace, unrack and stand with feet around shoulder width.|Bend knees and hips together to a controlled depth; stand through the whole foot.|barbell squat,barbell back squat
Front Squat|front-squat|Barbell|knee-dominant|Rack the bar on front shoulders with elbows high; use safety arms and a stable front-rack grip.|Sit down between hips with chest upright; stand without dropping elbows.|barbell front squat
Smith Machine Squat|smith-machine-squat|Smith machine|knee-dominant|Position bar across upper traps and feet where you can squat comfortably along the rail path. Set safety stops.|Unhook, squat under control with knees tracking toes, then stand.|smith squat
Hack Squat|hack-squat|Hack squat machine|knee-dominant|Place back and shoulders on the sled pads and feet on the angled platform. Set stops before unracking.|Lower the sled by bending knees; drive up without locking knees hard.|hack squat sled
Pendulum Squat|pendulum-squat|Pendulum squat machine|knee-dominant|Place shoulders beneath pads and back against support, feet on the fixed platform; set the safety catch.|Lower along the pivoting arm arc; stand through the whole foot.|pendulum machine squat
Leg Press|leg-press|Leg press machine|leg-press|Sit in a 45-degree sled leg press with back supported, feet shoulder-width on the platform and safety catches ready.|Lower until before hips curl off the pad; press the sled away without snapping knees straight.|45 degree leg press,sled press
Single-Leg Press|single-leg-press|Leg press machine|leg-press|Sit with pelvis square and one foot centered on the sled platform; use a light load and engage safeties.|Bend the working knee under control; press through the whole foot while pelvis stays level.|one leg press
Bulgarian Split Squat|bulgarian-split-squat|Dumbbells and bench|lunge|Stand in front of a low bench, rear foot resting on it, front foot planted far enough forward for balance.|Lower the back knee toward the floor; drive through the front leg to stand.|rear foot elevated split squat,rfess
Walking Lunge|walking-lunge|Dumbbells|lunge|Stand tall with dumbbells at sides and clear space ahead.|Step forward, lower back knee toward floor, then push through front foot and bring rear leg forward into the next step.|walking dumbbell lunge
Reverse Lunge|reverse-lunge|Dumbbells|lunge|Stand with feet hip-width and dumbbells at sides.|Step one foot backward and lower; push through the front foot to return, then alternate.|backward lunge
Step-Up|step-up|Dumbbells and box|lunge|Face a stable box at a height you can control; place the whole lead foot on top.|Drive through the lead leg to stand on the box; step down slowly with minimal push from the trailing foot.|box step up
Dumbbell Hip Thrust|dumbbell-hip-thrust|Dumbbell and bench|hip-extension|Rest upper back on a stable bench, feet flat, and hold a padded dumbbell across the hip crease.|Raise hips until torso is level; keep chin tucked and lower hips slowly.|hip thrust,weighted hip thrust
Barbell Hip Thrust|barbell-hip-thrust|Barbell and bench|hip-extension|Rest upper back on a stable bench and position a padded barbell over the hip crease, feet flat.|Extend hips until torso is level without over-arching; lower under control.|barbell glute thrust
Machine Hip Thrust|machine-hip-thrust|Hip thrust machine|hip-extension|Adjust the back support and secure the padded belt or hip pad across the pelvis, feet on the platform.|Drive hips upward against resistance; return while maintaining foot pressure.|glute drive machine
Cable Glute Kickback|cable-glute-kickback|Cable|glute-isolation|Attach an ankle cuff to a low machine pulley. Face the tower and hold a stable support, working leg connected by the cuff.|Move the working leg backward from the hip; return without rotating pelvis or arching.|cable kickback,ankle strap kickback
Hip Abduction Machine|hip-abduction-machine|Selectorized machine|abduction|Sit against the back pad with outer knees or thighs against the pads.|Open legs outward from hips; return slowly without slamming pads.|abductor machine,outer thigh machine
Conventional Deadlift|conventional-deadlift|Barbell|deadlift|Stand with bar above mid-foot, bend hips and knees to grip just outside legs, brace with a neutral back.|Push the floor away and stand with bar close; hinge and bend knees to lower it.|deadlift,barbell deadlift
Dumbbell Romanian Deadlift|dumbbell-romanian-deadlift|Dumbbells|hinge|Stand with dumbbells in front of thighs and knees slightly bent.|Send hips backward as weights track close to legs; return to standing when hamstrings limit depth.|dumbbell rdl,db rdl
Stiff-Leg Deadlift|stiff-leg-deadlift|Barbell|hinge|Stand with a barbell at thighs and knees only slightly unlocked. Use a light load and controlled range.|Hinge back while keeping knee angle nearly constant; stop before the back rounds and stand.|stiff legged deadlift
Trap-Bar Deadlift|trap-bar-deadlift|Trap bar|deadlift|Stand centered inside a hex bar, grip both side handles and brace with hips and knees bent.|Push the floor away to stand tall; lower by bending hips and knees together.|hex bar deadlift
Lying Leg Curl|lying-leg-curl|Selectorized machine|leg-curl|Lie face down with knees near the pivot and roller above the back of the ankles.|Curl heels toward glutes while hips stay on the pad; lower slowly.|prone hamstring curl
Standing Single-Leg Curl|standing-single-leg-curl|Leg curl machine|leg-curl|Adjust the standing machine so the working knee aligns with its pivot and roller sits above the ankle.|Bend the working knee to draw heel back; lower without moving the hip.|standing hamstring curl
Nordic Hamstring Curl|nordic-hamstring-curl|Nordic bench|leg-curl|Kneel on a padded Nordic bench with ankles secured under its padded support. Keep a straight line from knees to shoulders and hands ready to catch.|Lean forward slowly from the knees; catch with hands and assist the return as needed.|nordic curl,assisted nordic
Good Morning|good-morning|Barbell|hinge|Rest a light bar across upper traps, feet around hip-width and knees softly bent.|Push hips backward as torso tips forward; stop before back position changes and stand.|barbell good morning
Standing Calf Raise|standing-calf-raise|Bodyweight|calf|Stand on a stable step with balls of feet supported and heels free; hold a support for balance.|Rise onto toes; lower heels slowly through a comfortable range.|bodyweight standing calf raise
Seated Calf Raise|seated-calf-raise|Calf raise machine|calf|Sit with knees bent beneath thigh pads and balls of feet on the platform.|Lift heels, pause, then lower under control while knees stay bent.|bent knee calf raise
Leg-Press Calf Raise|leg-press-calf-raise|Leg press machine|calf|Sit in a leg press with back supported, balls of feet on the platform and knees slightly unlocked; set safeties.|Move only at ankles to press the sled away; lower heels without slipping.|calf press,toe press
Smith Machine Calf Raise|smith-machine-calf-raise|Smith machine|calf|Set bar across upper traps and balls of feet on a secure step, with safety stops set.|Rise through ankles; lower heels slowly while body remains upright.|smith calf raise
Single-Leg Calf Raise|single-leg-calf-raise|Bodyweight|calf|Stand on one foot on a stable step and hold a support; keep working knee softly unlocked.|Raise heel, pause, then lower slowly. Repeat on both sides.|one leg calf raise
Machine Crunch|machine-crunch|Selectorized machine|core-flexion|Adjust the seat and chest or shoulder pad to the machine design, feet supported.|Curl ribs toward pelvis against the pad; return slowly.|ab crunch machine
Reverse Crunch|reverse-crunch|Bodyweight|leg-raise|Lie on your back with hips and knees bent, arms beside you.|Curl pelvis off the floor to bring knees toward chest; lower without swinging.|reverse abdominal crunch
Hanging Knee Raise|hanging-knee-raise|Pull-up bar|leg-raise|Hang from a secure bar with shoulders controlled and knees bent.|Raise knees and curl pelvis forward; lower without swinging.|hanging knee lift
Hanging Leg Raise|hanging-leg-raise|Pull-up bar|leg-raise|Hang from a secure bar with legs extended and shoulders controlled.|Raise legs as far as you can without swinging, adding a pelvic curl; lower slowly.|hanging straight leg raise
Captain’s-Chair Knee Raise|captains-chair-knee-raise|Captain's chair|leg-raise|Support forearms on pads with back against the support and legs hanging.|Lift knees toward chest with a small pelvic curl; lower without swinging.|captains chair raise,vertical knee raise,vkr
Ab-Wheel Rollout|ab-wheel-rollout|Ab wheel|brace|Kneel on a pad with both hands on the wheel beneath shoulders, glutes and abs braced.|Roll forward only as far as you can keep the lower back steady; pull back to start.|ab roller,roll out
Side Plank|side-plank|Bodyweight|side-brace|Lie on one side, elbow under shoulder and feet stacked or staggered.|Lift hips to form a straight line; hold while breathing, then switch sides.|side bridge
Pallof Press|pallof-press|Cable|anti-rotation|Stand side-on to a machine pulley at chest height. Hold one handle with both hands against the chest and brace.|Press hands straight forward without turning toward the cable; draw back to chest.|anti rotation press
Russian Twist|russian-twist|Bodyweight|rotation|Sit with knees bent and feet grounded, torso leaned back slightly with a long spine, hands together.|Rotate the rib cage gently from side to side while hips remain steady.|seated torso twist
Cable Woodchop|cable-woodchop|Cable|rotation|Stand side-on to a high machine pulley, hold one handle with both hands and feet spaced for balance.|Draw handle diagonally downward across the body with controlled torso and hip rotation; return.|wood chop,high to low cable chop
Treadmill Run|treadmill-run|Treadmill|cardio|Attach the safety clip and build from walking to a manageable running speed.|Run with short controlled strides under your body; slow the belt before stepping off.|treadmill running,jogging
Incline Treadmill Walk|incline-treadmill-walk|Treadmill|cardio|Attach safety clip, start walking, then increase incline gradually.|Walk uphill with a slight whole-body lean; avoid supporting body weight on the rails.|incline treadmill,hill walk
Stair Climber|stair-climber|Stair machine|cardio|Step onto the stopped machine, identify its stop control and begin at a slow speed.|Take controlled steps with whole feet supported as practical; use rails lightly for balance.|stairmaster,stepmill
Elliptical|elliptical|Elliptical machine|cardio|Step onto pedals while holding fixed handles; select a comfortable resistance.|Move pedals in a smooth continuous cycle with upright posture.|cross trainer
Stationary Bike|stationary-bike|Exercise bike|cardio|Adjust saddle so the knee stays slightly bent at the bottom of the pedal stroke.|Pedal smoothly with relaxed shoulders and controlled cadence.|upright bike,spin bike,cycling
Recumbent Bike|recumbent-bike|Recumbent bike|cardio|Adjust seat distance so knees remain slightly bent at full pedal reach, back supported.|Pedal steadily without locking knees or rocking the pelvis.|recumbent cycle
Rowing Machine|rowing-machine|Rowing ergometer|cardio|Secure feet in straps and sit tall holding the handle with arms straight and knees bent.|Drive legs first, then open hips and pull handle to lower ribs; recover arms, hips, then knees.|rower,erg,rowing erg
Sled Push|sled-push|Sled|cardio|Load a push sled on suitable turf, grip its uprights and lean forward with a braced torso.|Take short powerful steps to drive the sled forward while keeping arms stable.|prowler push
'''
catalog=[]
for line in rows.strip().splitlines():
 name,slug,equipment,group,setup,movement,aliases=line.split('|');primary,secondary,region,pattern,lo,hi,cue,mistakes=groups[group]
 unilateral=bool(re.search(r'One-Arm|Single|Alternating|Cross-Body|Bayesian|Concentration|Leaning|Lunge|Split Squat|Step-Up|Side Plank',name))
 classification='cardio' if group=='cardio' else 'timed' if group in ['brace','side-brace'] and slug not in ['ab-wheel-rollout'] else 'bodyweight' if equipment.startswith('Bodyweight') or equipment in ['Pull-up bar','Parallel bars',"Captain's chair",'Nordic bench','Ab wheel'] else 'weighted'
 difficulty='Advanced' if slug in ['pendlay-row','nordic-hamstring-curl','good-morning','ab-wheel-rollout','hanging-leg-raise','front-squat','decline-barbell-bench-press'] else 'Beginner' if 'machine' in equipment.lower() or group in ['cardio','calf','pressdown'] else 'Intermediate'
 if slug=='close-grip-bench-press':primary,secondary='Triceps',['Chest','Anterior deltoids']
 legacy=slug in ['neutral-grip-pulldown','leg-press-or-squat','walking-lunge-or-split-squat']
 media_slug={'neutral-grip-pulldown':'neutral-grip-lat-pulldown','leg-press':'leg-press-or-squat'}.get(slug,slug)
 catalog.append(dict(name=name,slug=slug,canonical_name=name,aliases=aliases.split(','),primary_muscle=primary,secondary_muscles=secondary,body_region=region,movement_type=pattern,movement_pattern=pattern,equipment=equipment,laterality='Unilateral' if unilateral else 'Bilateral',exercise_type=classification,difficulty=difficulty,setup_instructions=setup,movement_instructions=movement,cue=cue,common_mistakes=mistakes,rest_min_seconds=lo,rest_max_seconds=hi,substitution_group=group,thumbnail_url=f'./media/thumbs/{media_slug}.webp',image_url=f'./media/{media_slug}.webp',motion_url=f'./media/{media_slug}.webp',motion_kind='still' if slug in ['russian-twist','incline-treadmill-walk'] else 'two-position',load_basis='per_dumbbell' if 'dumbbell' in equipment.lower() and equipment!='Dumbbell' and slug!='goblet-squat' else 'total',is_legacy=legacy))
assert len({e['slug'] for e in catalog})==len(catalog)
Path('data/exercises.json').write_text(json.dumps(catalog,indent=2,ensure_ascii=False)+'\n')
print(len(catalog),'total;',sum(not x['is_legacy'] for x in catalog),'selectable')
print('New artwork needed',len({x['image_url'] for x in catalog if not Path(x['image_url']).exists()}))
